[package]
name = "userinfos2"
version = "0.4.0"
authors = ["Rrogntudju"]
edition = "2021"
build = "build/build.rs"

[dependencies]
iced = { version = "0.9.0", features = ["tokio", "image"] }
iced_native = "0.10.3"
iced_core = "0.9.0"
iced_futures = "0.6.0"
cosmic-time = "0.2"
serde_json = "1"
oauth2 = { version = "4", default-features = false, features = ["ureq"]}
webbrowser = "0.8"
url = "2"
ureq = { version = "2", features = ["json"] }
anyhow = "1"
windows = { version = "0.48", features = ["UI_ViewManagement", "Foundation"] }
tokio = { version = "1", features = [ "sync" ] }

[build-dependencies]
winres = "0.1"