[package]
name = "userinfos2"
version = "0.3.0"
authors = ["Rrogntudju"]
edition = "2021"
build = "build/build.rs"

[dependencies]
iced = { version = "0.9", features = ["tokio", "image"] }
iced_native = "0.10"
serde_json = "1"
oauth2 = { version = "4", features = ["reqwest"]}
webbrowser = "0.8"
url = "2"
ureq = { version = "2", features = ["json"] }
anyhow = "1"
windows = { version = "0.48", features = ["UI_ViewManagement", "Foundation"] }
tokio = { version = "1", features = [ "sync" ] }

[build-dependencies]
winres = "0.1"