[package]
name = "userinfos2"
version = "0.2.0"
authors = ["Rrogntudju"]
edition = "2021"


[dependencies]
iced = { version = "0.9", features = ["tokio", "image"] }
serde_json = "1"
oauth2 = { version = "4", features = ["reqwest"]}
webbrowser = "0.8"
url = "2"
ureq = { version = "2", features = ["json"] }
anyhow = "1"

