[workspace]
resolver = "2"
members = [ "crates/*" ]

[profile.release]
opt-level = 3
lto = "thin"

[patch.crates-io]
palette = { git = "https://github.com/Ogeon/palette", branch = "issue_283_into_iterator" }