[package]
name = "server"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
warp = "0.2"
tokio = {version = "0.2", features = ["macros"]}
oidc = "0.3"
rand = "0.7"
lazy_static = "1"
chrono = "0.4"
reqwest = "0.9"
serde_json = "1"