[package]
name = "server"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
warp = {version = "0.2", features = ["tls"]}
tokio = {version = "0.2", features = ["macros"]}
oidc = {git = "https://gitlab.com/zanny/oidc-reqwest.git"}
inth-oauth2 = "0.16"
rand = "0.7"
lazy_static = "1"
reqwest = "0.9"
serde_json = "1"